### ISSUE TITLE
[Suggestion] Implement IP Geolocation Reverse Lookup using IP2Location.io API

### ISSUE THREAD

**Issue by ip2location** [TSERATO/GeoLoc#1]
@TSERATO 

I would like to introduce the IP2Location.io API for use in the GeoLoc Minecraft Plugin. IP2Location.io API is faster and accurate compare with other providers.

https://api.ip2location.io/?ip=8.8.8.8

`{
"ip":"8.8.8.8",
"country_code":"US",
"country_name":"United States of America",
"region_name":"California",
"city_name":"Mountain View",
"latitude":37.38605,
"longitude":-122.08385,
"zip_code":"94035",
"time_zone":"-07:00",
"asn":"15169",
"as":"Google LLC",
"is_proxy":false,
"message":"Limit to 500 queries per day. Sign up for a Free plan at https://www.ip2location.io to get 30K queries per month."
}`

**Comment by TSERATO** [comment]
Hello, 
the current API I am using has the same features as yours does, but I do not include them into my plugin, because they arent useful.
Kind Regards,
Alex!
